# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://azenium.ru'
baseurl: ''
title: 'Мастерская авторских курсов "Азениум"'
description: 'Авторские курсы на самые разные темы'
# permalink: pretty
logo: "/android-chrome-512x512.png"
favicons:
- [16, /favicon-16x16.png]
- [32, /favicon-32x32.png]
- [192, /android-chrome-192x192.png]
- [512, /android-chrome-512x512.png]

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Курсы
  url: /courses/index.html
- title: Обратная связь
  url: /feedback.html
- title: Социальное
  url: /social.html
- title: Обо мне
  url: /about.html
- title: Новости
  url: /news/news.html
- title: Помощь
  url: /help/index.html

# Footer nav
navigation_footer:
- title: Наверх
  url: "#top"

# Collections
collections:
  posts:
    title: Новости
    output: true
    description: "Текущая жизнь проекта"
    feature_text: |
      ## Все, что происходит с сайтом и курсами
    feature_image: "/news/news.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
