# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://howto-start.ru'
baseurl: ''
title: 'Как начать'
description: 'Как начать самые важные перемены в своей жизни'
# permalink: pretty
logo: "/puzzle.jpg"
favicons:
- [16, favicon-16x16.png]
- [32, favicon-32x32.png]
- [192, android-chrome-192x192.png]
- [512, android-chrome-512x512.png]

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Главная
  url: /
- title: Обо мне
  url: /about.html
- title: Курсы
  url: /courses/index.html
- title: Обратная связь
  url: /feedback.html

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
